{{- if and .Values.huggingface.tokenEnabled (not .Values.huggingface.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm.hfSecretName" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.huggingface.token | quote }}
{{- end }}
